
- hosts: all

  sudo: yes

  vars:
    repos:
      # EPEL
      - http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
      # REMI
      - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    repo: remi
    apps:
      - libselinux-python
      - mysql
      - mysql-server

  tasks:
    - name: Upgrade all packages
      yum: name=* state=latest

    - name: Add repos
      yum: name={{ item }} state=installed
      with_items: repos

    - name: Install apps
      yum: name={{ item }} enablerepo={{ repo }} state=latest
      with_items: apps

    - name: Enable automatically starting MySQL server
      service: name=mysqld state=started enabled=yes

    - name: Disable SELinux
      selinux: state=disabled

